version: "3"

services:
  app:
    image: mavedb/production:${MAVEDB_RELEASE_TAG}
    volumes:
      - celery-logs:/var/log/celery/
      - app-logs:/srv/app/logs/
      - media-files:/srv/app/media/
      - static-files:/srv/app/static
    env_file:
      - settings/.settings-production.env
    environment:
      - RUN_TESTS=$MAVEDB_RUN_TESTS
      - APP_VERSION=$MAVEDB_RELEASE_TAG
      - ENVIRONMENT=production
      - DJANGO_SETTINGS_MODULE=settings.production

  database:
    image: postgres:9.6
    restart: always
    ports:
      - $MAVEDB_DB_PORT:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $MAVEDB_DB_USER
      POSTGRES_PASSWORD: $MAVEDB_DB_PASSWORD
      POSTGRES_DB: $MAVEDB_DB_NAME

  broker:
    image: rabbitmq:3.8.3
    restart: always
    ports:
      - $MAVEDB_BROKER_PORT:5672

  server:
    build:
      context: ./nginx
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - static-files:/srv/app/static/
      - media-files:/srv/app/media/
      - server-logs:/var/log/nginx/

volumes:
  celery-logs:
  app-logs:
  static-files:
  media-files:
  server-logs:
  database-data:
