version: "3"

services:
  app:
    build:
      context: .
      args:
        DJANGO_REQUIREMENTS: development
    volumes:
      - .:/srv/app/
    env_file:
      - settings/.settings-development.env
    environment:
      - APP_VERSION=latest
      - ENVIRONMENT=development
      - DJANGO_SETTINGS_MODULE=settings.development
    ports:
      - "8000:8000"

  database:
    image: postgres:9.6
    ports:
      - $MAVEDB_DB_PORT:5432
    volumes:
      - dev-database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $MAVEDB_DB_USER
      POSTGRES_PASSWORD: $MAVEDB_DB_PASSWORD
      POSTGRES_DB: $MAVEDB_DB_NAME

  broker:
    image: rabbitmq:3.8.3
    ports:
      - $MAVEDB_BROKER_PORT:5672

volumes:
  dev-database-data:
